Update example of `nargo prove` usage
Running `nargo prove p` as currently indicated by this tutorial results in:

```
➜  noir_hello_world nargo prove p
error: unexpected argument 'p' found
```

The current version of `nargo` instead expects this to be `nargo prove -p p`, which yields the expected results.